credentials:
  usernames:
    user1:
      name: User One
      password: hashed_password1  # Replace with actual hashed password
    user2:
      name: User Two
      password: hashed_password2
    user3:
      name: User Three
      password: hashed_password3
    user4:
      name: User Four
      password: hashed_password4
    user5:
      name: User Five
      password: hashed_password5
cookie:
  name: ghatz_dashboard
  key: some_random_key_here  # Replace with a random string
  expiry_days: 30