# .streamlit/secrets.toml

[usernames]

[usernames.user1]
name = "User One"
password = "$2b$12$KSW2Ylf0URxyoJ6iYuAAUur7fDP7HgRYahAg.myaVEcRKHlNXJlMS"  # bcrypt hash of password

[usernames.admin]
name = "Admin User"
password = "$2b$12$UJw6rxavfOTiolUFS/ai2.6sMFKyTvI/eN4VLgdtTkKooZHHL/.8q"  # bcrypt hash of password

[cookie]
name = "ghatz_auth"
key = "supersecretkey123"
expiry_days = 7

[gcp_service_account]
type = "service_account"
project_id = "ghatz-458400"
private_key_id = "c8f8145f067ddb62f6ba515b3ae377f50198fc20"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDQZYhp8gbpEWhF
8pcmg/7ILJcGnW9Vvu+yipFpBPhZpJicgdgsI74qGm6hAeZ5Vd71t3+phu1K2a7x
idPaS3E6UrjNB5vohYSmcKsApTW9ortrYsU0sMpPrBJT8cfvcGeisDanFw4myQ8F
ojFoMWhU4HswRsmunmhwgeK+QiTUd8NGJh95C3YCAyKwwPZCUPHbYaiRPYEral//
0B7oegQHHW8bWzQ74QXnI5Ok8H59fql8rk4rVi0RzsDquCa8iWVWL/emXn7/8jk8
KUF+JypEZcdUGFYc6Lwr7qHIrdULT+LorLCNnt8jo061Vj7p3d+kTOU0Csl5Dn6u
klrEMLwzAgMBAAECggEALdKtkLI1v8jil0LU5pSukMBxQvSaNw4Bcc5TU/bSTw/I
uN06NdZ0KZjfS4r57SMrH/eF3DZ9dfBwrc7DJSRilNL8rKSoLRQyy1BJ4Z3yN60R
Lfctar0W9zbcXtXywx0BxL2fftUseO3L3k7AM2ttyAAGRmLCVSGi0F5XB8POimMX
mSfRV22m3oF55GrqpUzZvjdfKJ6YkTT3E4XBwPek8GrDkXqVOXemE69Jgc2ybZ/+
GG+2RRuwENuUGweEeyTrohCO6F/WxagkfJNbRT3wfksg0trALrDJCTQDikSNoeJQ
DNQaVs5x5FkV4bQZ1J0B9PFKvcDimdj7RsstSOQN/QKBgQDpr6yCobmvLc39awWS
C/D5ghCE4mVO2afcDrPQdXtTjglaiutwQXkr181q3MQ0+XoTwxjGKrYS780MhJLp
rbaBD58J39efZUFx6iZmhw7Z1+xiqB12HMXGNKp7V8cLvjBpJI2G+OutXpA3JWum
AQTWBL4W0MVNFE76QQYLmMw0NwKBgQDkS6s62JAnDuV9bF+3BzWXYyXSdBd6/Wlw
Aopzy7bXV1/9W+mFo/bbm8CMp3beYRNurdqWngE13OhmO1tQf6ZiycGGZPC2s2ls
cwwxiA1d6XcgS5h5mKOnb8pwZBdmy+KETpiHWqX7lPfEAlJ5/G+3s6Cu6F9D5/m0
Kn7eZ/Sx5QKBgDp1uzdW1Afx8oVCH7ughyE0G4PSyztFkguoFe3BZh/J+acP98Q2
bOS98OKZ5e/GtXZ6KRlyF+h22xoVlFcnIO/6g3PJ7rwubYfc5sxhXyK6NKWdnvks
S4HBLSD8HYxfgObcwRcR8IuHi5ZwIxT9TkNoHlHA2ork2LkcSTHfgL5TAoGAQFmX
7WFn2KqZQ25N2IB+uapn2deBWtidZMZCkntEkZR+aSMEQvhBuAtCDiOSHQLOAG+e
4r+s5arcExz+E0W397aZBzHirA0MVVZkhH2uDt+lBYRpeTTuRF79eAqukfo8YkDp
O5XwnWaTJDvnVZ0zPFu0mjjDyZdUylUEJ9qznYUCgYB3yp2dj5GZBYHMgwz1nsXs
Qj9dtSS88ep8kiUH+R+HSIc1nXDh6DtZ4u7dLkg4aZ1ZTzauExHiiPVeXYh39Cgb
X1UHNguCp0peFPaqSg96aFiY8m64MaqcY3BUwfWa8VghwDwprbd/v94nLsqxkl75
jbLZWtxd2pc4RyMXZi9b9w==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-sheets@ghatz-458400.iam.gserviceaccount.com"
client_id = "108883162156121206734"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets%40ghatz-458400.iam.gserviceaccount.com"
